### ISSUE TITLE
请问遇到“Graph is finalized and cannot be modified.”错误，要如何解决？

### ISSUE THREAD

**Issue by ghost** [TmengT/bert-django#1]
![image](https://user-images.githubusercontent.com/43852251/72530603-ab6f1100-38aa-11ea-8f02-7b581eae7b57.png)

**Comment by TmengT** [comment]
应该是没有bert 的model文件，需要在https://github.com/google-research/bert 下载下 BERT-Base, Chinese 模型，放到的 项目下，具体路径：..\nlp_api\models\chinese_L-12_H-768_A-12

**Comment by ghost** [comment]
先前已下载预训练模型至相应文件夹。应该不是这个问题。
![image](https://user-images.githubusercontent.com/43852251/72700199-1e67d880-3b86-11ea-9e0d-bbe24114e336.png)
